#!groovy

pipeline {
  agent any
  stages {
    stage('Docker Compose') {
            steps {
              sh 'docker-compose -f $WORKSPACE/pipeline-2_files/petclinic-docker-compose.yml up -d && docker-compose logs -f'
      }
    }
      
  } 
}
