#!groovy

pipeline {
  agent any
  stages {
    stage('Docker Compose') {
            steps {
        sh 'cd pipeline-2_files'
        sh ' docker-compose up -d && docker-compose logs -f'
      }
    }
      
  } 
}
