version: '3'

services:
   db:
     image: mysql:5.7.8
     volumes:
       - $PWD/src/main/resources/db/mysql:/home/mysql
     environment:
       MYSQL_ROOT_PASSWORD: petclinic
       MYSQL_DATABASE: petclinic
     command:
      - /bin/bash -c "ls -artl"
     container_name: db
   app1:
     depends_on:
       - db
     image: gitaau/petclinic-image:latest
     container_name: petc1
     ports:
       - "8091:8080"
     restart: always
   app2:
     depends_on:
      - db
     image: gitaau/petclinic-image:latest
     container_name: petc2
     ports:
       - "8092:8080"
     restart: always
   nginx:
     depends_on:
       - app1
       - app2
     image: nginx
     container_name: nginx
     volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf
     links:
       - app1:app1
       - app2:app2
       - db:db
     ports:
       - 80:80
